version: '2'
services:
  webA:
    image: kingdaddyfreshness/docker-intro-1:latest 
    ports: 
        - "9007:8080"
  webB:
    image: kingdaddyfreshness/docker-intro-2:latest
    ports: 
        - "9008:8080"
  webC:
    image: kingdaddyfreshness/docker-intro-3:latest
    ports: 
        - "9009:8080"
