version: '2'

services:
  webA:
    image: my1
    ports: 
        - "9007:8080"
    volumes:
        - /Users/jhilgedick/src/Sandbox/compose-test/logs1:/usr/local/tomcat/logs
    
  webB:
    image: my4
    environment:
        WEBA: now is the time
        WEBB: later please
    links:
        - webA
    ports: 
        - "9008:8080"
    volumes:
        - /Users/jhilgedick/src/Sandbox/compose-test/logs2:/usr/local/tomcat/logs
        
    
  webC:
    image: my5
    ports: 
        - "9009:8080"
    volumes:
        - /Users/jhilgedick/src/Sandbox/compose-test/logs3:/usr/local/tomcat/logs
